### ISSUE TITLE
Support custom destination folder

### ISSUE THREAD

**Issue by dantehemerson** [swinton/screenshot-website#28]
I want to add to destination into the working folder.

**Comment by spier** [comment]
Just adding that I would also use a feature to set a custom destination folder.

Right now I have a step in my workflow right after screenshote-website runs, that will copy the generated screenshot to where I want it to be like this:

```
    - name: Screenshot Markmap Website
      id: screenshot-generator
      uses: swinton/screenshot-website@main
      with:
        <<removed as not helpful for example>>
    - name: Copy Screenshot
      run: cp ${{ steps.screenshot-generator.outputs.path }} .
```
